services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000" # Map Symfony's built-in server to localhost:8000
    volumes:
      - .:/app:cached # Sync project files for live updates
    depends_on:
      - db
    environment:
      APP_ENV: dev
      DATABASE_URL: "postgresql://symfony:symfony@db:5432/symfony"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
      POSTGRES_DB: symfony
    volumes:
      - db-data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "8080:80" # Nginx on localhost:8080
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/app:cached
    depends_on:
      - web

  adminer:
    image: adminer:latest
    ports:
      - "8081:8080" # Adminer on localhost:8081
    environment:
      ADMINER_DEFAULT_SERVER: db # Nom du service de la base de données dans Docker

volumes:
  db-data:
